#server:
#  servlet:
    # context-path: /springboot   # 访问的应用名
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl